yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    # Доступно всем
    path('', views.index,
         name='main_page'
         ),
    path('group/<slug:slug>/', views.group_posts,
         name='group_list'
         ),
    path('profile/<str:username>/', views.profile,
         name='profile'
         ),
    path('posts/<int:post_id>/', views.post_detail,
         name='post_detail'
         ),
    # Доступно авторизованному пользователю
    path('create/', views.post_create,
         name='create_post'
         ),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'
         ),
    path('follow/', views.follow_index,
         name='follow_index'
         ),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'
         ),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'
         ),
    # Доступно автору
    path('posts/<post_id>/edit/', views.post_edit,
         name='post_edit'
         ),
    path('posts/<post_id>/delete/', views.post_delete,
         name='post_delete'
         ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler403, handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('auth/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from core.models import CreatedModel
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

LEN_POST: int = 15


class Group(models.Model):
    title = models.CharField(
        verbose_name='Группа',
        help_text='Выберите группу для поста',
        max_length=200)
    slug = models.SlugField(
        verbose_name='Слаг группы',
        unique=True)
    description = models.TextField(
        verbose_name='Описание группы',
        help_text='Введите описание группы'
    )

    def __str__(self) -> str:
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )


class Comment(models.Model):
    text = models.TextField('Текст', help_text='Текст нового комментария')
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='comments',
        verbose_name='Ссылка на пост'
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(
        verbose_name='Комментарий'
    )
    created = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )

    def __str__(self):
        return self.text[:LEN_POST]

    class Meta:
        ordering = ['created']
        verbose_name = "Комментарий"
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        help_text='Подписчик автора'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
        help_text='Автор публикаций'
    )

    class Meta:
        db_table = 'Follow'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_follow')
        ]
        verbose_name_plural = 'Подписки'

yatube/posts/forms.py
from xml.etree.ElementTree import Comment

from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["text", "group", "image", ]
        labels = {'text': 'Текст', 'group': 'Группа', 'image': 'Картинка', }
        help_texts = {'text': 'Введите текст публикации',
                      'group': 'Выберите группу', }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Текст', }
        help_text = {'text': 'Введите текст комментария', }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import paginator

POST_COUNT: int = 10


@cache_page(20, key_prefix='index_page')
def index(request):
    posts = Post.objects.all()
    page_obj = paginator(posts, request, POST_COUNT)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()  # type: ignore
    page_obj = paginator(posts, request, POST_COUNT)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()  # type: ignore
    page_obj = paginator(posts, request, POST_COUNT)
    follow = Follow.objects.filter(author=author)
    following = follow.exists() and request.user.is_authenticated
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect('posts:profile', request.user)
    return render(request, "posts/create_post.html", {"form": form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post.save()
        return redirect("posts:post_detail", post_id)
    return render(request, "posts/create_post.html", {"form": form,
                                                      "post": post,
                                                      "is_edit": True})


@login_required
def add_comment(request, post_id):
    post = Post.objects.get(id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.delete()
    return redirect('posts:profile', request.user)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user).all()
    page_obj = paginator(posts, request, POST_COUNT)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(user=request.user, author=author).exists()
    if not follow and username != request.user.username:
        Follow.objects.create(user=request.user, author=author)
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    query = Follow.objects.filter(user=request.user, author=author)
    if query.exists():
        query.delete()
    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
Редактировать
{% else %}
Новая запись
{% endif %}
{% endblock %}
{% block content %}
{% load user_filters %}

<body>
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              {% if is_edit %}
              Редактировать пост
              {% else %}
              Новый пост
              {% endif %}
            </div>
            <div class="card-body">
              <form method="post" action={% if is_edit %} "{% url 'posts:post_edit' post_id=post.id %}"
                {% else %} "{% url 'posts:create_post' %}" {% endif %} enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  {% for field in form %}
                  <label for="id_text">
                    {{ field.label }}
                    {% if field.field.required %}
                    <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {{ field|addclass:"form-control" }}
                  <small>
                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                  </small>
                  {% endfor %}
                </div>
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                    Сохранить
                    {% else %}
                    Опубликовать
                    {% endif %}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</body>
{% endblock %}

</html>

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Подписки{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}

{% for post in page_obj %}
{% include 'posts/includes/posts_list.html'%}
{% endfor %}


{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Группа: {{ group }}{% endblock %}
{% block content %}
<h1> {{ group.title }}</h1>
<article>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
  {% include 'posts/includes/posts_list.html'%}
  {% endfor %}
  {% include 'includes/paginator.html' %}
  {% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Все посты{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% for post in page_obj %}
{% include 'posts/includes/posts_list.html'%}
{% endfor %}

{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="ru">

<head>
  {% block title %}{{ post.author.get_full_name }}: "{{ post.text|truncatechars:30 }}..."{% endblock %}
</head>

<body>
  {% block content %}
  <main>
    <div class="row">
      {% include 'posts/includes/content.html' %}
      {% include 'posts/includes/editing.html' %}
      {% include 'posts/includes/comments.html' %}
      </article>
    </div>
  </main>
  {% endblock %}
</body>

</html>

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="ru">

<head>
  {% block title %}Профайл пользователя: {{ author.get_full_name }}{% endblock %}
</head>

<body>
  {% block content %}
  <main>
    <div class="container py-5">
      <h1>
        <center>{{ author.get_full_name }}</center>
      </h1>
      <h5>Всего постов: {{ author.posts.count }} </h5>
      <article>
        {% if user != author %}
        {% if following %}
        <a class="btn btn-lg btn-light" href="{% url 'posts:profile_unfollow' author.username %}" role="button">
          Отписаться
        </a>
        {% else %}
        <a class="btn btn-lg btn-primary" href="{% url 'posts:profile_follow' author.username %}" role="button">
          Подписаться
        </a>
        {% endif %}
        {% endif %}
        {% for post in page_obj %}
        {% include 'posts/includes/posts_list.html'%}
        {% endfor %}
        {% include 'includes/paginator.html' %}
    </div>
  </main>
  {% endblock %}
</body>

</html>